# Generated by Django 5.1.1 on 2025-01-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tarea',
            table='sgt',
        ),
    ]
