# Generated by Django 5.1.1 on 2025-01-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_alter_tarea_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(db_column='sgt_completada', default=False),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(db_column='sgt_descripcion'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_column='sgt_fechaCreacion'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, db_column='sgt_fechaVencimiento', null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(db_column='sgt_titulo', max_length=200),
        ),
        migrations.AlterModelTable(
            name='tarea',
            table='sgt',
        ),
    ]
