# Generated by Django 5.1.1 on 2025-01-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_alter_tarea_completada_alter_tarea_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tarea',
            table=None,
        ),
    ]
